# Generated by Django 4.2.4 on 2023-08-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('info', models.TextField()),
            ],
            options={
                'verbose_name': 'Biz xaqimizda',
                'verbose_name_plural': 'Biz xaqimizda',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('title', models.TextField(verbose_name="Ma'lumot")),
                ('info', models.TextField(verbose_name="Footer uchun ma'lumot")),
                ('img', models.ImageField(upload_to='', verbose_name='Rasm')),
                ('tel', models.CharField(max_length=13, verbose_name='TelRaqam')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Bosh sahifa',
                'verbose_name_plural': 'Bosh sahifa',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Servis nomi')),
                ('title', models.CharField(max_length=250, verbose_name="Qisqacha ma'lumot")),
                ('img', models.ImageField(upload_to='', verbose_name='svg rasm')),
            ],
            options={
                'verbose_name': 'Xizmatlar',
                'verbose_name_plural': 'Xizmatlar',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('info', models.CharField(max_length=100, verbose_name='Mutaxasisligi')),
                ('title', models.TextField(verbose_name="Ma'lumot")),
            ],
            options={
                'verbose_name': 'Fikirlar',
                'verbose_name_plural': 'Fikirlar',
            },
        ),
    ]
